//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.CodeFirst.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PONTO
    {
        public int ID_PONTO { get; set; }
        public int ID_FUNCIONARIO { get; set; }
        public System.DateTime DT_PONTO { get; set; }
    
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
    }
}
