//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/04/2015 12:21:42
namespace LGroup.AcessaEdmxRemoto.ProxyOData
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LGroup.Service.EdmxRemoto.DataAccess", "LGroup.AcessaEdmxRemoto.ProxyOData");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LGroup.AcessaEdmxRemoto.ProxyOData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LGroup.Service.EdmxRemoto.DataAccess.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for TB_PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TB_PRODUTO> TB_PRODUTO
        {
            get
            {
                if ((this._TB_PRODUTO == null))
                {
                    this._TB_PRODUTO = base.CreateQuery<TB_PRODUTO>("TB_PRODUTO");
                }
                return this._TB_PRODUTO;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TB_PRODUTO> _TB_PRODUTO;
        /// <summary>
        /// There are no comments for TB_PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTB_PRODUTO(TB_PRODUTO tB_PRODUTO)
        {
            base.AddObject("TB_PRODUTO", tB_PRODUTO);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = @"<edmx:Edmx Version=""1.0"" xmlns:edmx=""http://schemas.microsoft.com/ado/2007/06/edmx""><edmx:DataServices m:DataServiceVersion=""3.0"" m:MaxDataServiceVersion=""3.0"" xmlns:m=""http://schemas.microsoft.com/ado/2007/08/dataservices/metadata""><Schema Namespace=""LGroup.Service.EdmxRemoto.DataAccess"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityType Name=""TB_PRODUTO""><Key><PropertyRef Name=""ID_PRODUTO"" /></Key><Property Name=""ID_PRODUTO"" Type=""Edm.Int32"" Nullable=""false"" /><Property Name=""NM_PRODUTO"" Type=""Edm.String"" /><Property Name=""NM_DESCRICAO"" Type=""Edm.String"" /><Property Name=""VL_PRODUTO"" Type=""Edm.Decimal"" Nullable=""false"" /><Property Name=""FLG_STATUS"" Type=""Edm.Boolean"" Nullable=""false"" /><Property Name=""NM_FORNECEDOR"" Type=""Edm.String"" /><Property Name=""NM_CATEGORIA"" Type=""Edm.String"" /></EntityType></Schema><Schema Namespace=""Default"" xmlns=""http://schemas.microsoft.com/ado/2009/11/edm""><EntityContainer Name=""Container"" m:IsDefaultEntityContainer=""true""><EntitySet Name=""TB_PRODUTO"" EntityType=""LGroup.Service.EdmxRemoto.DataAccess.TB_PRODUTO"" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LGroup.Service.EdmxRemoto.DataAccess.TB_PRODUTO in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID_PRODUTO
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TB_PRODUTO")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID_PRODUTO")]
    public partial class TB_PRODUTO : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TB_PRODUTO object.
        /// </summary>
        /// <param name="iD_PRODUTO">Initial value of ID_PRODUTO.</param>
        /// <param name="vL_PRODUTO">Initial value of VL_PRODUTO.</param>
        /// <param name="fLG_STATUS">Initial value of FLG_STATUS.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TB_PRODUTO CreateTB_PRODUTO(int iD_PRODUTO, decimal vL_PRODUTO, bool fLG_STATUS)
        {
            TB_PRODUTO tB_PRODUTO = new TB_PRODUTO();
            tB_PRODUTO.ID_PRODUTO = iD_PRODUTO;
            tB_PRODUTO.VL_PRODUTO = vL_PRODUTO;
            tB_PRODUTO.FLG_STATUS = fLG_STATUS;
            return tB_PRODUTO;
        }
        /// <summary>
        /// There are no comments for Property ID_PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID_PRODUTO
        {
            get
            {
                return this._ID_PRODUTO;
            }
            set
            {
                this.OnID_PRODUTOChanging(value);
                this._ID_PRODUTO = value;
                this.OnID_PRODUTOChanged();
                this.OnPropertyChanged("ID_PRODUTO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID_PRODUTO;
        partial void OnID_PRODUTOChanging(int value);
        partial void OnID_PRODUTOChanged();
        /// <summary>
        /// There are no comments for Property NM_PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_PRODUTO
        {
            get
            {
                return this._NM_PRODUTO;
            }
            set
            {
                this.OnNM_PRODUTOChanging(value);
                this._NM_PRODUTO = value;
                this.OnNM_PRODUTOChanged();
                this.OnPropertyChanged("NM_PRODUTO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_PRODUTO;
        partial void OnNM_PRODUTOChanging(string value);
        partial void OnNM_PRODUTOChanged();
        /// <summary>
        /// There are no comments for Property NM_DESCRICAO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_DESCRICAO
        {
            get
            {
                return this._NM_DESCRICAO;
            }
            set
            {
                this.OnNM_DESCRICAOChanging(value);
                this._NM_DESCRICAO = value;
                this.OnNM_DESCRICAOChanged();
                this.OnPropertyChanged("NM_DESCRICAO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_DESCRICAO;
        partial void OnNM_DESCRICAOChanging(string value);
        partial void OnNM_DESCRICAOChanged();
        /// <summary>
        /// There are no comments for Property VL_PRODUTO in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal VL_PRODUTO
        {
            get
            {
                return this._VL_PRODUTO;
            }
            set
            {
                this.OnVL_PRODUTOChanging(value);
                this._VL_PRODUTO = value;
                this.OnVL_PRODUTOChanged();
                this.OnPropertyChanged("VL_PRODUTO");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _VL_PRODUTO;
        partial void OnVL_PRODUTOChanging(decimal value);
        partial void OnVL_PRODUTOChanged();
        /// <summary>
        /// There are no comments for Property FLG_STATUS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool FLG_STATUS
        {
            get
            {
                return this._FLG_STATUS;
            }
            set
            {
                this.OnFLG_STATUSChanging(value);
                this._FLG_STATUS = value;
                this.OnFLG_STATUSChanged();
                this.OnPropertyChanged("FLG_STATUS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _FLG_STATUS;
        partial void OnFLG_STATUSChanging(bool value);
        partial void OnFLG_STATUSChanged();
        /// <summary>
        /// There are no comments for Property NM_FORNECEDOR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_FORNECEDOR
        {
            get
            {
                return this._NM_FORNECEDOR;
            }
            set
            {
                this.OnNM_FORNECEDORChanging(value);
                this._NM_FORNECEDOR = value;
                this.OnNM_FORNECEDORChanged();
                this.OnPropertyChanged("NM_FORNECEDOR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_FORNECEDOR;
        partial void OnNM_FORNECEDORChanging(string value);
        partial void OnNM_FORNECEDORChanged();
        /// <summary>
        /// There are no comments for Property NM_CATEGORIA in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NM_CATEGORIA
        {
            get
            {
                return this._NM_CATEGORIA;
            }
            set
            {
                this.OnNM_CATEGORIAChanging(value);
                this._NM_CATEGORIA = value;
                this.OnNM_CATEGORIAChanged();
                this.OnPropertyChanged("NM_CATEGORIA");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NM_CATEGORIA;
        partial void OnNM_CATEGORIAChanging(string value);
        partial void OnNM_CATEGORIAChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
