//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.Service.EdmxRemoto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO
    {
        public int ID_PRODUTO { get; set; }
        public string NM_PRODUTO { get; set; }
        public string NM_DESCRICAO { get; set; }
        public decimal VL_PRODUTO { get; set; }
        public bool FLG_STATUS { get; set; }
        public string NM_FORNECEDOR { get; set; }
        public string NM_CATEGORIA { get; set; }
    }
}
