//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.SysAmigos.UI.Windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AMIGO
    {
        public int ID_AMIGO { get; set; }
        public int ID_SEXO { get; set; }
        public string NM_AMIGO { get; set; }
        public string DS_EMAIL { get; set; }
        public string NR_TELEFONE { get; set; }
        public System.DateTime DT_NASCIMENTO { get; set; }
    
        public virtual TB_SEXO TB_SEXO { get; set; }
    }
}
