//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGroup.SysAmigos.UI.Windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public byte[] NM_USUARIO { get; set; }
        public string DS_SENHA { get; set; }
        public string NR_TELEFONE { get; set; }
        public string DS_EMAIL { get; set; }
    }
}
