// <auto-generated />
namespace LGroup.CodeFirst.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class EnderecoCpfMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnderecoCpfMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201503071259364_EnderecoCpfMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
